name: gitlab

services:
  gitlab:
    image: gitlab/gitlab-ce:17.6.5-ce.0
    container_name: gitlab
    restart: always
    hostname: '${HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}:8929'
    ports:
      - '8929:8929'
      - '443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
