name: gitlab

services:
  gitlab:
    image: gitlab/gitlab-ce:17.6.5-ce.0
    container_name: gitlab
    restart: always
    hostname: '${HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    secrets:
      - gitlab_root_password  
    ports:
      - '80:80'
      #- '443:443'
      - '2222:22'
    volumes:
      - './config/gitlab/config:/etc/gitlab'
      - './config/gitlab/logs:/var/log/gitlab'
      - './config/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

secrets:
  gitlab_root_password:
    file: ./root_password.txt
